-- El Terracampino — seed de la comarca completa (191 municipios, delimitación Wikipedia)
-- GENERADO por scripts/generate_municipios.mjs — no editar a mano.
-- Ejecutar DESPUÉS de schema.sql. Es seguro ejecutarlo después de seed_piloto.sql:
-- el "on conflict (slug) do nothing" respeta las filas piloto ya cargadas (con su
-- prioridad 1, población y coordenadas), y solo añade el resto de la comarca.
-- Fuente de la lista: https://es.wikipedia.org/wiki/Tierra_de_Campos

insert into municipalities (name, slug, province, comarca, priority, population, lat, lon, active, notes) values
  ('Abarca de Campos', 'abarca-de-campos', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Abia de las Torres', 'abia-de-las-torres', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Amayuelas de Arriba', 'amayuelas-de-arriba', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Ampudia', 'ampudia', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Amusco', 'amusco', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Arconada', 'arconada', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Autilla del Pino', 'autilla-del-pino', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Autillo de Campos', 'autillo-de-campos', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Baquerín de Campos', 'baquerin-de-campos', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Becerril de Campos', 'becerril-de-campos', 'Palencia', 'Tierra de Campos', 1, 737, 42.108333, -4.641667, true, 'Municipio piloto'),
  ('Belmonte de Campos', 'belmonte-de-campos', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Boada de Campos', 'boada-de-campos', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Boadilla de Rioseco', 'boadilla-de-rioseco', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Boadilla del Camino', 'boadilla-del-camino', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Bárcena de Campos', 'barcena-de-campos', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Calzada de los Molinos', 'calzada-de-los-molinos', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Capillas', 'capillas', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Cardeñosa de Volpejera', 'cardenosa-de-volpejera', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Carrión de los Condes', 'carrion-de-los-condes', 'Palencia', 'Tierra de Campos', 1, 1997, 42.338889, -4.601944, true, 'Municipio piloto'),
  ('Castil de Vela', 'castil-de-vela', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Castrillo de Villavega', 'castrillo-de-villavega', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Castromocho', 'castromocho', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Cervatos de la Cueza', 'cervatos-de-la-cueza', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Cisneros', 'cisneros', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Frechilla', 'frechilla', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Frómista', 'fromista', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Fuentes de Nava', 'fuentes-de-nava', 'Palencia', 'Tierra de Campos', 1, 581, 42.083056, -4.783056, true, 'Municipio piloto'),
  ('Fuentes de Valdepero', 'fuentes-de-valdepero', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Grijota', 'grijota', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Guaza de Campos', 'guaza-de-campos', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Husillos', 'husillos', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Itero de la Vega', 'itero-de-la-vega', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Lantadilla', 'lantadilla', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Lomas de Campos', 'lomas-de-campos', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Manquillos', 'manquillos', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Marcilla de Campos', 'marcilla-de-campos', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Mazariegos', 'mazariegos', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Mazuecos de Valdeginate', 'mazuecos-de-valdeginate', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Meneses de Campos', 'meneses-de-campos', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Monzón de Campos', 'monzon-de-campos', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Moratinos', 'moratinos', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Nogal de las Huertas', 'nogal-de-las-huertas', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Osornillo', 'osornillo', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Osorno', 'osorno', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Palencia', 'palencia', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Paredes de Nava', 'paredes-de-nava', 'Palencia', 'Tierra de Campos', 1, 1927, 42.152778, -4.694444, true, 'Municipio piloto'),
  ('Pedraza de Campos', 'pedraza-de-campos', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Perales', 'perales', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Piña de Campos', 'pina-de-campos', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Población de Arroyo', 'poblacion-de-arroyo', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Población de Campos', 'poblacion-de-campos', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Pozo de Urama', 'pozo-de-urama', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Requena de Campos', 'requena-de-campos', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Revenga de Campos', 'revenga-de-campos', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Ribas de Campos', 'ribas-de-campos', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Riberos de la Cueza', 'riberos-de-la-cueza', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('San Cebrián de Campos', 'san-cebrian-de-campos', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('San Mamés de Campos', 'san-mames-de-campos', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('San Román de la Cuba', 'san-roman-de-la-cuba', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Santa Cecilia del Alcor', 'santa-cecilia-del-alcor', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Santoyo', 'santoyo', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Torremormojón', 'torremormojon', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Támara de Campos', 'tamara-de-campos', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Valde-Ucieza', 'valde-ucieza', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Valle del Retortillo', 'valle-del-retortillo', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villacidaler', 'villacidaler', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villada', 'villada', 'Palencia', 'Tierra de Campos', 1, 863, 42.25056, -4.96694, true, 'Municipio piloto'),
  ('Villaherreros', 'villaherreros', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villalcázar de Sirga', 'villalcazar-de-sirga', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villalcón', 'villalcon', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villalobón', 'villalobon', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villamartín de Campos', 'villamartin-de-campos', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villamoronta', 'villamoronta', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villamuera de la Cueza', 'villamuera-de-la-cueza', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villanueva del Rebollar', 'villanueva-del-rebollar', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villarmentero de Campos', 'villarmentero-de-campos', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villarramiel', 'villarramiel', 'Palencia', 'Tierra de Campos', 1, 782, 42.0425, -4.913056, true, 'Municipio piloto'),
  ('Villasarracino', 'villasarracino', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villaturde', 'villaturde', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villaumbrales', 'villaumbrales', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villerías de Campos', 'villerias-de-campos', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villoldo', 'villoldo', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villovieco', 'villovieco', 'Palencia', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Aguilar de Campos', 'aguilar-de-campos', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Barcial de la Loma', 'barcial-de-la-loma', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Becilla de Valderaduey', 'becilla-de-valderaduey', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Berrueces', 'berrueces', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Bolaños de Campos', 'bolanos-de-campos', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Bustillo de Chaves', 'bustillo-de-chaves', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Cabezón de Valderaduey', 'cabezon-de-valderaduey', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Cabreros del Monte', 'cabreros-del-monte', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Castrobol', 'castrobol', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Castroponce de Valderaduey', 'castroponce-de-valderaduey', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Ceinos de Campos', 'ceinos-de-campos', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Cuenca de Campos', 'cuenca-de-campos', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Fontihoyuelo', 'fontihoyuelo', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Gatón de Campos', 'gaton-de-campos', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Gordaliza de la Loma', 'gordaliza-de-la-loma', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Herrín de Campos', 'herrin-de-campos', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('La Unión de Campos', 'la-union-de-campos', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Mayorga', 'mayorga', 'Valladolid', 'Tierra de Campos', 1, 1354, 42.16663, -5.2627, true, 'Municipio piloto'),
  ('Medina de Rioseco', 'medina-de-rioseco', 'Valladolid', 'Tierra de Campos', 1, 4617, 41.883056, -5.042778, true, 'Municipio piloto'),
  ('Melgar de Abajo', 'melgar-de-abajo', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Melgar de Arriba', 'melgar-de-arriba', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Monasterio de Vega', 'monasterio-de-vega', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Montealegre de Campos', 'montealegre-de-campos', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Moral de la Reina', 'moral-de-la-reina', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Morales de Campos', 'morales-de-campos', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Palazuelo de Vedija', 'palazuelo-de-vedija', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Pozuelo de la Orden', 'pozuelo-de-la-orden', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Quintanilla del Molar', 'quintanilla-del-molar', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Roales de Campos', 'roales-de-campos', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Saelices de Mayorga', 'saelices-de-mayorga', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('San Pedro de Latarce', 'san-pedro-de-latarce', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Santa Eufemia del Arroyo', 'santa-eufemia-del-arroyo', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Santervás de Campos', 'santervas-de-campos', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Tamariz de Campos', 'tamariz-de-campos', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Tordehumos', 'tordehumos', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Urones de Castroponce', 'urones-de-castroponce', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Valdunquillo', 'valdunquillo', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Valverde de Campos', 'valverde-de-campos', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Vega de Ruiponce', 'vega-de-ruiponce', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villabaruz de Campos', 'villabaruz-de-campos', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villabrágima', 'villabragima', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villacarralón', 'villacarralon', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villacid de Campos', 'villacid-de-campos', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villafrades de Campos', 'villafrades-de-campos', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villafrechós', 'villafrechos', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villagarcía de Campos', 'villagarcia-de-campos', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villagómez la Nueva', 'villagomez-la-nueva', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villalán de Campos', 'villalan-de-campos', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villalba de la Loma', 'villalba-de-la-loma', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villalón de Campos', 'villalon-de-campos', 'Valladolid', 'Tierra de Campos', 1, 1473, 42.098449, -5.034713, true, 'Municipio piloto'),
  ('Villamuriel de Campos', 'villamuriel-de-campos', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villanueva de la Condesa', 'villanueva-de-la-condesa', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villanueva de los Caballeros', 'villanueva-de-los-caballeros', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villanueva de San Mancio', 'villanueva-de-san-mancio', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villardefrades', 'villardefrades', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villavicencio de los Caballeros', 'villavicencio-de-los-caballeros', 'Valladolid', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Belver de los Montes', 'belver-de-los-montes', 'Zamora', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Castronuevo de los Arcos', 'castronuevo-de-los-arcos', 'Zamora', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Castroverde de Campos', 'castroverde-de-campos', 'Zamora', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Cañizo de Campos', 'canizo-de-campos', 'Zamora', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Cerecinos de Campos', 'cerecinos-de-campos', 'Zamora', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Cotanes del Monte', 'cotanes-del-monte', 'Zamora', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Granja de Moreruela', 'granja-de-moreruela', 'Zamora', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Prado', 'prado', 'Zamora', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Quintanilla del Monte', 'quintanilla-del-monte', 'Zamora', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Quintanilla del Olmo', 'quintanilla-del-olmo', 'Zamora', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Revellinos', 'revellinos', 'Zamora', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('San Agustín del Pozo', 'san-agustin-del-pozo', 'Zamora', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('San Esteban del Molar', 'san-esteban-del-molar', 'Zamora', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('San Martín de Valderaduey', 'san-martin-de-valderaduey', 'Zamora', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('San Miguel del Valle', 'san-miguel-del-valle', 'Zamora', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Tapioles', 'tapioles', 'Zamora', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Valdescorriel', 'valdescorriel', 'Zamora', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Vega de Villalobos', 'vega-de-villalobos', 'Zamora', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Vidayanes', 'vidayanes', 'Zamora', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villafáfila', 'villafafila', 'Zamora', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villalba de la Lampreana', 'villalba-de-la-lampreana', 'Zamora', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villalobos', 'villalobos', 'Zamora', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villalpando', 'villalpando', 'Zamora', 'Tierra de Campos', 1, 1433, 41.864722, -5.413056, true, 'Municipio piloto'),
  ('Villamayor de Campos', 'villamayor-de-campos', 'Zamora', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villanueva del Campo', 'villanueva-del-campo', 'Zamora', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villar de Fallaves', 'villar-de-fallaves', 'Zamora', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villárdiga', 'villardiga', 'Zamora', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villarrín de Campos', 'villarrin-de-campos', 'Zamora', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Almanza', 'almanza', 'León', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Bercianos del Real Camino', 'bercianos-del-real-camino', 'León', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('El Burgo Ranero', 'el-burgo-ranero', 'León', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Calzada del Coto', 'calzada-del-coto', 'León', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Campazas', 'campazas', 'León', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Castilfalé', 'castilfale', 'León', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Castrotierra de Valmadrigal', 'castrotierra-de-valmadrigal', 'León', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Cea', 'cea', 'León', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Escobar de Campos', 'escobar-de-campos', 'León', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Fuentes de Carbajal', 'fuentes-de-carbajal', 'León', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Gordaliza del Pino', 'gordaliza-del-pino', 'León', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Gordoncillo', 'gordoncillo', 'León', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Grajal de Campos', 'grajal-de-campos', 'León', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Izagre', 'izagre', 'León', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Joarilla de las Matas', 'joarilla-de-las-matas', 'León', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Matanza de los Oteros', 'matanza-de-los-oteros', 'León', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Sahagún', 'sahagun', 'León', 'Tierra de Campos', 1, 2380, 42.371111, -5.033056, true, 'Municipio piloto'),
  ('Valderas', 'valderas', 'León', 'Tierra de Campos', 1, 1479, 42.0775, -5.4425, true, 'Municipio piloto'),
  ('Valdemora', 'valdemora', 'León', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Vallecillo', 'vallecillo', 'León', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Valverde-Enrique', 'valverde-enrique', 'León', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villabraz', 'villabraz', 'León', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villamol', 'villamol', 'León', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)'),
  ('Villazanzo de Valderaduey', 'villazanzo-de-valderaduey', 'León', 'Tierra de Campos', 3, null, null, null, true, 'Comarca (base geográfica Wikipedia)')
on conflict (slug) do nothing;
